spring:
  application:
    name: e-invoicing

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/e-invoicing-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      bootstrap-servers: localhost:9092
      group-id: normalizeInvoice
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: '*'

  datasource:
    url: jdbc:postgresql://localhost:5432/einvoicing
    username: postgres
    password: admin
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

server:
  port: 8082
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    oauth:
      client-id: e-invoicing

keycloak:
  auth-server-url: http://localhost:8080
  realm: e-invoicing-realm

webclient:
  baseurl: http://localhost:8083/dgiInvoice
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjAyMDIxMTI5NDYzNjV8VFMwMTAwOTc3MyIsInJvbGUiOiJUYXhwYXllciIsIm5iZiI6MTcxMjk0MDAwMSwiZXhwIjoxNzI4NzUxMjAxLCJpYXQiOjE3MTI5NDAwMDEsImlzcyI6ImltcG90cy5iaiIsImF1ZCI6ImltcG90cy5iaiJ9.uL1daGvFCltavZQ0394Hw-klOmckOap1gUoucOn5Z-M

jwt:
  auth:
    converter:
      resource-id: e-invoicing
      principal-attribute: preferred_username

topic:
  emcf: e-invoicing
  normalize : normalize-invoice