spring:
  application:
    name: e-invoicing

  datasource:
    url: jdbc:postgresql://localhost:5432/einvoicing
    username: postgres
    password: admin
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

server:
  port: 8082